-- Add video_url column to exercises table
alter table public.exercises add column if not exists video_url text;

-- CHEST
insert into public.exercises (name, primary_muscle, movement_pattern, equipment, progression_eligible, suggested_rep_min, suggested_rep_max) values
('Barbell Bench Press', 'chest', 'horizontal_press', 'barbell', true, 3, 12),
('Low Incline Barbell Bench Press', 'chest', 'horizontal_press', 'barbell', true, 4, 12),
('High Incline Barbell Bench Press', 'chest', 'horizontal_press', 'barbell', true, 4, 12),
('Paused Barbell Bench Press', 'chest', 'horizontal_press', 'barbell', true, 3, 8),
('Close Grip Bench Press', 'chest', 'horizontal_press', 'barbell', true, 4, 12),
('Incline Close Grip Bench', 'chest', 'horizontal_press', 'barbell', true, 4, 12),
('DB Bench Press', 'chest', 'horizontal_press', 'dumbbell', true, 6, 15),
('DB Low Incline Bench Press', 'chest', 'horizontal_press', 'dumbbell', true, 6, 15),
('High Incline DB Bench Press', 'chest', 'horizontal_press', 'dumbbell', true, 6, 15),
('DB Decline Bench Press', 'chest', 'horizontal_press', 'dumbbell', true, 6, 15),
('DB Flye Press', 'chest', 'horizontal_press', 'dumbbell', true, 8, 15),
('Cable Flyes (Low to High)', 'chest', 'isolation', 'cable', true, 10, 20),
('Cable Flyes (High to Low)', 'chest', 'isolation', 'cable', true, 10, 20),
('Cable Flyes (Neutral)', 'chest', 'isolation', 'cable', true, 10, 20),
('Pec Deck Flyes', 'chest', 'isolation', 'machine', true, 10, 20),
('Machine Flyes', 'chest', 'isolation', 'machine', true, 10, 20),
('Machine Bench Press', 'chest', 'horizontal_press', 'machine', true, 8, 15),
('Machine Incline Bench Press', 'chest', 'horizontal_press', 'machine', true, 8, 15),
('Machine Decline Bench Press', 'chest', 'horizontal_press', 'machine', true, 8, 15),
('Deficit Push Ups', 'chest', 'horizontal_press', 'bodyweight', false, 8, 20),
('Plyo Push Ups', 'chest', 'horizontal_press', 'bodyweight', false, 5, 15),
('DB Hex Press', 'chest', 'horizontal_press', 'dumbbell', true, 8, 15),
('Barbell Push Ups', 'chest', 'horizontal_press', 'barbell', false, 8, 20),
('Push Ups', 'chest', 'horizontal_press', 'bodyweight', false, 10, 30),
('Dips (Chest Focus)', 'chest', 'horizontal_press', 'bodyweight', true, 6, 15),
('Prowler (Tyson) Push Ups', 'chest', 'horizontal_press', 'bodyweight', false, 5, 15),
('Plate Push Ups', 'chest', 'horizontal_press', 'bodyweight', false, 8, 20);

-- BACK
insert into public.exercises (name, primary_muscle, movement_pattern, equipment, progression_eligible, suggested_rep_min, suggested_rep_max) values
('Pull Ups', 'back', 'vertical_pull', 'bodyweight', true, 4, 12),
('Neutral Grip Pull Ups', 'back', 'vertical_pull', 'bodyweight', true, 4, 12),
('Chin Ups', 'back', 'vertical_pull', 'bodyweight', true, 4, 12),
('Weighted Pull Ups', 'back', 'vertical_pull', 'bodyweight', true, 3, 10),
('Assisted Pull Ups', 'back', 'vertical_pull', 'machine', false, 6, 15),
('Assisted Chin Ups', 'back', 'vertical_pull', 'machine', false, 6, 15),
('Wide Grip Lat Pulldown', 'back', 'vertical_pull', 'cable', true, 8, 15),
('Narrow Grip Lat Pulldown', 'back', 'vertical_pull', 'cable', true, 8, 15),
('Close Grip Lat Pulldown', 'back', 'vertical_pull', 'cable', true, 8, 15),
('Reverse Grip Lat Pulldown', 'back', 'vertical_pull', 'cable', true, 8, 15),
('Machine Lat Pulldown', 'back', 'vertical_pull', 'machine', true, 8, 15),
('Machine Row (Prone Grip)', 'back', 'horizontal_pull', 'machine', true, 8, 15),
('Machine Row (Narrow Grip)', 'back', 'horizontal_pull', 'machine', true, 8, 15),
('Machine Low Row', 'back', 'horizontal_pull', 'machine', true, 8, 15),
('Hammer Rows', 'back', 'horizontal_pull', 'machine', true, 8, 15),
('Seated Cable Row', 'back', 'horizontal_pull', 'cable', true, 8, 15),
('DB Row', 'back', 'horizontal_pull', 'dumbbell', true, 6, 15),
('Chest Supported DB Rows', 'back', 'horizontal_pull', 'dumbbell', true, 8, 15),
('T-Bar Rows', 'back', 'horizontal_pull', 'barbell', true, 6, 12),
('Wide Grip Cable Rows', 'back', 'horizontal_pull', 'cable', true, 8, 15),
('Single Arm Cable Rows', 'back', 'horizontal_pull', 'cable', true, 8, 15),
('Towel Pull Ups', 'back', 'vertical_pull', 'bodyweight', false, 4, 10),
('Inverted Rows', 'back', 'horizontal_pull', 'bodyweight', false, 8, 15),
('Barbell Rows', 'back', 'horizontal_pull', 'barbell', true, 5, 12),
('Smith Machine Rows', 'back', 'horizontal_pull', 'smith_machine', true, 6, 12),
('Yates Row', 'back', 'horizontal_pull', 'barbell', true, 6, 12),
('DB Bent Over Row', 'back', 'horizontal_pull', 'dumbbell', true, 6, 12),
('Pendlay Rows', 'back', 'horizontal_pull', 'barbell', true, 4, 8),
('Dead Rows', 'back', 'horizontal_pull', 'barbell', true, 4, 8),
('Lat Prayers (Straight Arm Pulldown)', 'back', 'vertical_pull', 'cable', true, 10, 20),
('DB Pullover', 'back', 'vertical_pull', 'dumbbell', true, 10, 15),
('Meadows Rows', 'back', 'horizontal_pull', 'barbell', true, 8, 15),
('DB Rear Delt Rows', 'back', 'horizontal_pull', 'dumbbell', true, 10, 20),
('Seal Rows', 'back', 'horizontal_pull', 'barbell', true, 6, 12),
('DB Seal Rows', 'back', 'horizontal_pull', 'dumbbell', true, 8, 15),
('Rack Chins', 'back', 'vertical_pull', 'bodyweight', false, 6, 15),
('Kelso Shrugs', 'back', 'horizontal_pull', 'barbell', true, 10, 20),
('Barbell Deadlift', 'back', 'hinge', 'barbell', true, 1, 6),
('Rack Pulls', 'back', 'hinge', 'barbell', true, 2, 6),
('Snatch Grip Deadlift', 'back', 'hinge', 'barbell', true, 2, 6),
('Snatch Grip Rack Pulls', 'back', 'hinge', 'barbell', true, 2, 6);
