-- SHOULDERS / DELTS
insert into public.exercises (name, primary_muscle, movement_pattern, equipment, progression_eligible, suggested_rep_min, suggested_rep_max) values
('Barbell Overhead Press', 'delts', 'vertical_press', 'barbell', true, 3, 10),
('Seated DB Press', 'delts', 'vertical_press', 'dumbbell', true, 6, 15),
('High Incline DB Press', 'delts', 'vertical_press', 'dumbbell', true, 8, 15),
('DB Lateral Raise', 'delts', 'isolation', 'dumbbell', true, 10, 25),
('Eccentric DB Lateral Raise', 'delts', 'isolation', 'dumbbell', true, 8, 15),
('Machine Lateral Raise', 'delts', 'isolation', 'machine', true, 10, 20),
('Cable Lateral Raise', 'delts', 'isolation', 'cable', true, 10, 25),
('Inclined DB Lateral Raise', 'delts', 'isolation', 'dumbbell', true, 10, 20),
('Side Lying DB Lateral Raise', 'delts', 'isolation', 'dumbbell', true, 10, 20),
('Machine Shoulder Press', 'delts', 'vertical_press', 'machine', true, 8, 15),
('Cable Upright Rows', 'delts', 'isolation', 'cable', true, 10, 15),
('DB Upright Rows', 'delts', 'isolation', 'dumbbell', true, 10, 15),
('Crucifix Hold', 'delts', 'isolation', 'dumbbell', false, 1, 1),
('Cable Face Pull', 'delts', 'horizontal_pull', 'cable', true, 12, 25),
('DB Rear Delt Raises', 'delts', 'isolation', 'dumbbell', true, 12, 25),
('DB Rear Delt Swings', 'delts', 'isolation', 'dumbbell', false, 15, 30),
('DB Rear Delt Partials', 'delts', 'isolation', 'dumbbell', false, 15, 30),
('Reverse Pec Deck', 'delts', 'isolation', 'machine', true, 12, 20),
('Barbell Push Press', 'delts', 'vertical_press', 'barbell', true, 3, 8),
('DB Push Press', 'delts', 'vertical_press', 'dumbbell', true, 4, 10),
('DB Y Raise', 'delts', 'isolation', 'dumbbell', true, 12, 20),
('Barbell Z-Press', 'delts', 'vertical_press', 'barbell', true, 4, 10),
('DB Z-Press', 'delts', 'vertical_press', 'dumbbell', true, 6, 12),
('DB Front Raise', 'delts', 'isolation', 'dumbbell', true, 10, 20),
('Cable Front Raise', 'delts', 'isolation', 'cable', true, 10, 20),
('Iso-Dynamic DB Lateral Raise', 'delts', 'isolation', 'dumbbell', false, 10, 20),
('Sir Charles Lateral Raise', 'delts', 'isolation', 'dumbbell', false, 10, 20);

-- QUADS
insert into public.exercises (name, primary_muscle, movement_pattern, equipment, progression_eligible, suggested_rep_min, suggested_rep_max) values
('Barbell Back Squat', 'quads', 'squat', 'barbell', true, 3, 10),
('Barbell Front Squat', 'quads', 'squat', 'barbell', true, 3, 8),
('Zercher Squat', 'quads', 'squat', 'barbell', true, 4, 10),
('1/4 Back Squat', 'quads', 'squat', 'barbell', true, 4, 10),
('Hatfield Squat', 'quads', 'squat', 'barbell', true, 4, 15),
('1/4 Hatfield Squat', 'quads', 'squat', 'barbell', true, 4, 15),
('Pause Squat', 'quads', 'squat', 'barbell', true, 3, 6),
('No-Pause Squat', 'quads', 'squat', 'barbell', true, 4, 10),
('Anderson Squat', 'quads', 'squat', 'barbell', true, 3, 6),
('DB Bulgarian Split Squat', 'quads', 'lunge', 'dumbbell', true, 6, 15),
('Smith Bulgarian Split Squat', 'quads', 'lunge', 'smith_machine', true, 6, 15),
('DB 1/4 Rep Bulgarian Split Squat', 'quads', 'lunge', 'dumbbell', true, 6, 12),
('Barbell Lunges', 'quads', 'lunge', 'barbell', true, 6, 12),
('Barbell Reverse Lunges', 'quads', 'lunge', 'barbell', true, 6, 12),
('Smith Reverse Lunges', 'quads', 'lunge', 'smith_machine', true, 8, 15),
('DB Split Squat', 'quads', 'lunge', 'dumbbell', true, 8, 15),
('Smith Split Squat', 'quads', 'lunge', 'smith_machine', true, 8, 15),
('DB Walking Lunges', 'quads', 'lunge', 'dumbbell', false, 10, 20),
('Weighted Step Ups', 'quads', 'lunge', 'dumbbell', true, 8, 15),
('High-Box Step Ups', 'quads', 'lunge', 'dumbbell', true, 6, 12),
('Goblet Squats', 'quads', 'squat', 'dumbbell', true, 8, 20),
('1/4 Goblet Squats', 'quads', 'squat', 'dumbbell', true, 8, 15),
('Cyclist Squats', 'quads', 'squat', 'bodyweight', true, 10, 20),
('Hack Squats', 'quads', 'squat', 'machine', true, 6, 15),
('Leg Extensions', 'quads', 'isolation', 'machine', true, 10, 20),
('Leg Press', 'quads', 'squat', 'machine', true, 8, 20),
('Single Leg Press', 'quads', 'squat', 'machine', true, 8, 15),
('Cossack Squat', 'quads', 'squat', 'bodyweight', false, 8, 15),
('Alternating Jumping Lunges', 'quads', 'lunge', 'bodyweight', false, 10, 20),
('Backwards Sled Drag', 'quads', 'squat', 'machine', false, 1, 1),
('Barbell Sumo Squat', 'quads', 'squat', 'barbell', true, 6, 15),
('Belt Squats', 'quads', 'squat', 'machine', true, 8, 20),
('Box Squats', 'quads', 'squat', 'barbell', true, 3, 8),
('Drop Reverse Lunges', 'quads', 'lunge', 'dumbbell', true, 8, 15),
('Front Foot Elevated Split Squat', 'quads', 'lunge', 'dumbbell', true, 8, 15),
('Deficit Curtsy Lunge', 'quads', 'lunge', 'dumbbell', true, 8, 15),
('Zercher Lunges', 'quads', 'lunge', 'barbell', true, 6, 12),
('Lateral Step Ups', 'quads', 'lunge', 'dumbbell', true, 8, 15),
('Pendulum Squat', 'quads', 'squat', 'machine', true, 8, 20),
('SSB Squat', 'quads', 'squat', 'barbell', true, 4, 10),
('Machine Adduction', 'quads', 'isolation', 'machine', true, 12, 20);

-- HAMSTRINGS
insert into public.exercises (name, primary_muscle, movement_pattern, equipment, progression_eligible, suggested_rep_min, suggested_rep_max) values
('Seated Hamstring Curl', 'hamstrings', 'isolation', 'machine', true, 8, 15),
('Lying Hamstring Curls', 'hamstrings', 'isolation', 'machine', true, 8, 15),
('Barbell Romanian Deadlift', 'hamstrings', 'hinge', 'barbell', true, 6, 12),
('DB Romanian Deadlift', 'hamstrings', 'hinge', 'dumbbell', true, 8, 15),
('Smith RDL', 'hamstrings', 'hinge', 'smith_machine', true, 8, 15),
('Single Leg DB RDL', 'hamstrings', 'hinge', 'dumbbell', true, 8, 15),
('Single Leg Barbell RDL', 'hamstrings', 'hinge', 'barbell', true, 6, 12),
('Glute-Ham Raise (GHR)', 'hamstrings', 'hinge', 'machine', false, 4, 12),
('Slider Hamstring Curls', 'hamstrings', 'isolation', 'bodyweight', false, 6, 12),
('Zercher RDL', 'hamstrings', 'hinge', 'barbell', true, 6, 12),
('Single Leg Hamstring Curls (Lying)', 'hamstrings', 'isolation', 'machine', true, 8, 15),
('Single Leg Machine Hamstring Curls', 'hamstrings', 'isolation', 'machine', true, 8, 15);
