-- SWOLE/OS — Exercise Library v2 (full reseed) — matches live schema
ALTER TABLE public.exercises ADD COLUMN IF NOT EXISTS sub_group text;

DELETE FROM public.set_logs;
DELETE FROM public.session_exercises;
DELETE FROM public.workout_sessions;
DELETE FROM public.template_session_exercises;
DELETE FROM public.template_sessions;
DELETE FROM public.workout_templates;
DELETE FROM public.exercises;

INSERT INTO public.exercises (name, primary_muscle, movement_pattern, equipment, sub_group) VALUES
-- CHEST
('Barbell Bench Press','chest','horizontal_press','barbell',NULL),
('Low Incline Barbell Bench Press','chest','horizontal_press','barbell',NULL),
('High Incline Barbell Bench Press','chest','horizontal_press','barbell',NULL),
('Paused Barbell Bench Press','chest','horizontal_press','barbell',NULL),
('Smith Incline Press','chest','horizontal_press','smith_machine',NULL),
('DB Bench Press','chest','horizontal_press','dumbbell',NULL),
('DB Low Incline Bench Press','chest','horizontal_press','dumbbell',NULL),
('High Incline DB Bench Press','chest','horizontal_press','dumbbell',NULL),
('DB Decline Bench Press','chest','horizontal_press','dumbbell',NULL),
('DB Flye Press','chest','isolation','dumbbell',NULL),
('Cable Flyes (Low to High)','chest','isolation','cable',NULL),
('Cable Flyes (High to Low)','chest','isolation','cable',NULL),
('Cable Flyes (Neutral)','chest','isolation','cable',NULL),
('Pec Deck Flyes','chest','isolation','machine',NULL),
('Machine Flyes','chest','isolation','machine',NULL),
('Machine Bench Press','chest','horizontal_press','machine',NULL),
('Machine Incline Bench Press','chest','horizontal_press','machine',NULL),
('Machine Decline Bench Press','chest','horizontal_press','machine',NULL),
('Deficit Pushups','chest','horizontal_press','bodyweight',NULL),
('Plyo Pushups','chest','isolation','bodyweight',NULL),
('DB Hex Press','chest','horizontal_press','dumbbell',NULL),
('Incline DB Hex Press','chest','horizontal_press','dumbbell',NULL),
('Barbell Pushups','chest','horizontal_press','barbell',NULL),
('Push Ups','chest','horizontal_press','bodyweight',NULL),
('Prowler (Tyson) Push Ups','chest','horizontal_press','bodyweight',NULL),
('Plate Push Ups','chest','horizontal_press','bodyweight',NULL),
-- BACK WIDTH
('Pull Ups','back','vertical_pull','bodyweight','width'),
('Neutral Grip Pull Ups','back','vertical_pull','bodyweight','width'),
('Chin Ups','back','vertical_pull','bodyweight','width'),
('Weighted Pull Ups / Chin Ups','back','vertical_pull','bodyweight','width'),
('Assisted Pull Ups','back','vertical_pull','machine','width'),
('Assisted Chin Ups','back','vertical_pull','machine','width'),
('Rack Chins','back','vertical_pull','bodyweight','width'),
('Wide Grip Lat Pulldowns','back','vertical_pull','cable','width'),
('Narrow Grip Lat Pulldowns','back','vertical_pull','cable','width'),
('Close Grip Lat Pulldowns','back','vertical_pull','cable','width'),
('Reverse Grip Lat Pulldowns','back','vertical_pull','cable','width'),
('Single Arm Lat Pulldowns','back','vertical_pull','cable','width'),
('Cobra Lat Pulldowns','back','vertical_pull','cable','width'),
('Machine Lat Pulldowns','back','vertical_pull','machine','width'),
('Neutral Grip Rows','back','horizontal_pull','cable','width'),
('Machine Row (Lat-Focused / Narrow Grip)','back','horizontal_pull','machine','width'),
('Machine Low Row','back','horizontal_pull','machine','width'),
('Single Arm Hammer Rows (Machine)','back','horizontal_pull','machine','width'),
('Seated Cable Row (Close Grip)','back','horizontal_pull','cable','width'),
('DB Row','back','horizontal_pull','dumbbell','width'),
('DB Pullover','back','isolation','dumbbell','width'),
('Lat Prayers (Straight Arm Pulldown)','back','isolation','cable','width'),
-- BACK THICKNESS
('Chest Supported DB Rows','back','horizontal_pull','dumbbell','thickness'),
('T-Bar Rows','back','horizontal_pull','barbell','thickness'),
('Wide Grip Cable Rows','back','horizontal_pull','cable','thickness'),
('Single Arm Cable Rows','back','horizontal_pull','cable','thickness'),
('Inverted Rows','back','horizontal_pull','bodyweight','thickness'),
('Barbell Rows','back','horizontal_pull','barbell','thickness'),
('Smith Machine Rows','back','horizontal_pull','smith_machine','thickness'),
('Yates Row','back','horizontal_pull','barbell','thickness'),
('DB Bent Over Row','back','horizontal_pull','dumbbell','thickness'),
('Pendlay Rows','back','horizontal_pull','barbell','thickness'),
('Meadows Rows','back','horizontal_pull','barbell','thickness'),
('DB Rear Delt Rows','back','horizontal_pull','dumbbell','thickness'),
('Seal Rows','back','horizontal_pull','barbell','thickness'),
('DB Seal Rows','back','horizontal_pull','dumbbell','thickness'),
('DB Kelso Shrugs','back','isolation','dumbbell','thickness'),
('Barbell Deadlift','back','hinge','barbell','thickness'),
('Rack Pulls','back','hinge','barbell','thickness'),
('Snatch Grip Deadlift','back','hinge','barbell','thickness'),
('Snatch Grip Rack Pulls','back','hinge','barbell','thickness'),
-- DELTS
('Barbell Overhead Press','delts','vertical_press','barbell',NULL),
('Smith Overhead Press','delts','vertical_press','smith_machine',NULL),
('Seated Military Press','delts','vertical_press','barbell',NULL),
('Seated DB Press','delts','vertical_press','dumbbell',NULL),
('High Incline DB Press','delts','vertical_press','dumbbell',NULL),
('DB Lateral Raise','delts','isolation','dumbbell',NULL),
('Eccentric DB Lateral Raise','delts','isolation','dumbbell',NULL),
('Machine Lateral Raise','delts','isolation','machine',NULL),
('Cable Lateral Raise','delts','isolation','cable',NULL),
('Inclined DB Lateral Raise','delts','isolation','dumbbell',NULL),
('Side Lying DB Lateral Raise','delts','isolation','dumbbell',NULL),
('Machine Shoulder Press','delts','vertical_press','machine',NULL),
('Cable Upright Rows','delts','vertical_pull','cable',NULL),
('DB Upright Rows','delts','vertical_pull','dumbbell',NULL),
('Crucifix Hold','delts','isolation','dumbbell',NULL),
('Cable Face Pull','delts','horizontal_pull','cable',NULL),
('DB Rear Delt Raises','delts','isolation','dumbbell',NULL),
('DB Rear Delt Swings','delts','isolation','dumbbell',NULL),
('DB Rear Delt Partials','delts','isolation','dumbbell',NULL),
('Cable Rear Delt Flyes','delts','isolation','cable',NULL),
('Reverse Pec Deck','delts','isolation','machine',NULL),
('Barbell Push Press','delts','vertical_press','barbell',NULL),
('DB Push Press','delts','vertical_press','dumbbell',NULL),
('DB Y Raise','delts','isolation','dumbbell',NULL),
('Barbell Z-Press','delts','vertical_press','barbell',NULL),
('DB Z-Press','delts','vertical_press','dumbbell',NULL),
('DB Front Raise','delts','isolation','dumbbell',NULL),
('Cable Front Raise','delts','isolation','cable',NULL),
('Iso-Dynamic DB Lateral Raise','delts','isolation','dumbbell',NULL),
('Sir Charles Lateral Raise','delts','isolation','dumbbell',NULL),
-- QUADS
('Barbell Back Squat','quads','squat','barbell',NULL),
('Barbell Front Squat','quads','squat','barbell',NULL),
('Zercher Squat','quads','squat','barbell',NULL),
('1+1/4 Back Squat','quads','squat','barbell',NULL),
('Hatfield Squat','quads','squat','barbell',NULL),
('1+1/4 Hatfield Squat','quads','squat','barbell',NULL),
('Pause Squat','quads','squat','barbell',NULL),
('No-Pause Squat','quads','squat','barbell',NULL),
('Anderson Squat','quads','squat','barbell',NULL),
('DB Bulgarian Split Squat','quads','lunge','dumbbell',NULL),
('Smith Bulgarian Split Squat','quads','lunge','smith_machine',NULL),
('DB 1+1/4 Rep Bulgarian Split Squat','quads','lunge','dumbbell',NULL),
('Barbell Lunges','quads','lunge','barbell',NULL),
('Barbell Reverse Lunges','quads','lunge','barbell',NULL),
('Smith Reverse Lunges','quads','lunge','smith_machine',NULL),
('DB Split Squat','quads','lunge','dumbbell',NULL),
('Smith Split Squat','quads','lunge','smith_machine',NULL),
('DB Walking Lunges','quads','lunge','dumbbell',NULL),
('Weighted Step Ups','quads','lunge','dumbbell',NULL),
('High-Box Step Ups','quads','lunge','dumbbell',NULL),
('Goblet Squats','quads','squat','dumbbell',NULL),
('1+1/4 Goblet Squats','quads','squat','dumbbell',NULL),
('Cyclist Squats','quads','squat','barbell',NULL),
('Hack Squats','quads','squat','machine',NULL),
('Leg Extensions','quads','isolation','machine',NULL),
('Leg Press','quads','squat','machine',NULL),
('Single Leg Press','quads','squat','machine',NULL),
('Cossack Squat','quads','lunge','bodyweight',NULL),
('Alternating Jumping Lunges','quads','isolation','bodyweight',NULL),
('Backwards Sled Drag','quads','carry','machine',NULL),
('Barbell Sumo Squat','quads','squat','barbell',NULL),
('Belt Squats','quads','squat','machine',NULL),
('Box Squats','quads','squat','barbell',NULL),
('Drop Reverse Lunges','quads','lunge','dumbbell',NULL),
('Front Foot Elevated Split Squat','quads','lunge','dumbbell',NULL),
('Squat / Lunge / Step Up Complex','quads','lunge','dumbbell',NULL),
('Deficit Curtsy Lunge','quads','lunge','dumbbell',NULL),
('Zercher Lunges','quads','lunge','barbell',NULL),
('Lateral Step Ups','quads','lunge','dumbbell',NULL),
('Pendulum Squat','quads','squat','machine',NULL),
('SSB Squat','quads','squat','barbell',NULL),
('Machine Adduction','quads','isolation','machine',NULL),
-- HAMSTRINGS
('Seated Hamstring Curl','hamstrings','isolation','machine',NULL),
('Lying Hamstring Curls','hamstrings','isolation','machine',NULL),
('Barbell Romanian Deadlift','hamstrings','hinge','barbell',NULL),
('DB Romanian Deadlift','hamstrings','hinge','dumbbell',NULL),
('Smith RDL','hamstrings','hinge','smith_machine',NULL),
('Single Leg DB RDL','hamstrings','hinge','dumbbell',NULL),
('Single Leg Barbell RDL','hamstrings','hinge','barbell',NULL),
('Glute-Ham Raise (GHR)','hamstrings','isolation','bodyweight',NULL),
('Slider Hamstring Curls','hamstrings','isolation','bodyweight',NULL),
('Zercher RDL','hamstrings','hinge','barbell',NULL),
('Single Leg Hamstring Curls (Lying)','hamstrings','isolation','machine',NULL),
('Single Leg Machine Hamstring Curls','hamstrings','isolation','machine',NULL),
-- BICEPS
('Barbell Curls','biceps','isolation','barbell',NULL),
('EZ Bar Curls','biceps','isolation','barbell',NULL),
('Spider Curls','biceps','isolation','dumbbell',NULL),
('Barbell Reverse Curls','biceps','isolation','barbell',NULL),
('DB Hammer Curls','biceps','isolation','dumbbell',NULL),
('DB Incline Curls','biceps','isolation','dumbbell',NULL),
('DB Incline Hammer Curls','biceps','isolation','dumbbell',NULL),
('DB Preacher Curls','biceps','isolation','dumbbell',NULL),
('Machine Preacher Curls','biceps','isolation','machine',NULL),
('Cable Rope Curls','biceps','isolation','cable',NULL),
('Cable Curls','biceps','isolation','cable',NULL),
('Single Arm Cable Curl','biceps','isolation','cable',NULL),
('Seated Curls (Dead Stop)','biceps','isolation','dumbbell',NULL),
('Seated DB Curls','biceps','isolation','dumbbell',NULL),
('Gironda Perfect Curls','biceps','isolation','barbell',NULL),
('Plate Curls','biceps','isolation','bodyweight',NULL),
('1+1/4 DB Hammer Curls','biceps','isolation','dumbbell',NULL),
('Zottman Curls','biceps','isolation','dumbbell',NULL),
('Machine Biceps Curl','biceps','isolation','machine',NULL),
('Alternating DB Curls','biceps','isolation','dumbbell',NULL),
-- TRICEPS
('Close Grip Push Up','triceps','horizontal_press','bodyweight',NULL),
('Close Grip Bench Press','triceps','horizontal_press','barbell',NULL),
('Close Grip Incline Press','triceps','horizontal_press','barbell',NULL),
('Barbell Floor Press','triceps','horizontal_press','barbell',NULL),
('Lying DB Triceps Extension','triceps','isolation','dumbbell',NULL),
('DB Lateral Triceps Extension','triceps','isolation','dumbbell',NULL),
('Cable Rope Pushdown','triceps','isolation','cable',NULL),
('Cable Bar Pushdown','triceps','isolation','cable',NULL),
('JM Press','triceps','horizontal_press','barbell',NULL),
('PJR Pullovers','triceps','isolation','barbell',NULL),
('Cable Overhead Triceps Extension','triceps','isolation','cable',NULL),
('Inverted Skull Crusher','triceps','isolation','barbell',NULL),
('Banded Triceps Pushdown','triceps','isolation','bands',NULL),
('Paused DB Triceps Extension','triceps','isolation','dumbbell',NULL),
('Dips','triceps','horizontal_press','bodyweight',NULL),
('Skull Crushers','triceps','isolation','barbell',NULL),
('Smith Close Grip Bench Press','triceps','horizontal_press','smith_machine',NULL),
('Machine Triceps Extension','triceps','isolation','machine',NULL),
-- CALVES
('Machine Calf Raise','calves','isolation','machine',NULL),
('Seated Calf Raise','calves','isolation','machine',NULL),
('Barbell Calf Raise','calves','isolation','barbell',NULL),
('Rockback Calf Raise','calves','isolation','bodyweight',NULL),
('Donkey Calf Raise','calves','isolation','machine',NULL),
('DB Calf Raise','calves','isolation','dumbbell',NULL),
('Machine Calf Extension','calves','isolation','machine',NULL),
-- GLUTES
('Barbell Hip Thrust','glutes','isolation','barbell',NULL),
('Smith Machine Hip Thrust','glutes','isolation','smith_machine',NULL),
('45 Degree Back Extension','glutes','isolation','bodyweight',NULL),
('Frog Pumps','glutes','isolation','bodyweight',NULL),
('Cable Kickbacks','glutes','isolation','cable',NULL),
('Machine Kickbacks','glutes','isolation','machine',NULL),
('Machine Abduction','glutes','isolation','machine',NULL),
('1+1/4 Hip Thrust','glutes','isolation','barbell',NULL),
('Pause Hip Thrust','glutes','isolation','barbell',NULL),
('Triple Pulse Hip Thrust','glutes','isolation','barbell',NULL),
('B-Stance Hip Thrust','glutes','isolation','barbell',NULL),
('Banded Lateral Shuffle','glutes','isolation','bands',NULL),
('DB Walking Lunges (Long Stride)','glutes','lunge','dumbbell',NULL),
('Glute Bridge Walkouts','glutes','isolation','bodyweight',NULL),
('Glute Bridge March','glutes','isolation','bodyweight',NULL),
('Cable Pull Throughs','glutes','isolation','cable',NULL),
('Pulse Hip Thrusts','glutes','isolation','barbell',NULL),
('B-Stance RDL','glutes','hinge','dumbbell',NULL),
('Banded Hip Abduction','glutes','isolation','bands',NULL),
('Side Lying Hip Raise','glutes','isolation','bodyweight',NULL),
('Standing Abduction','glutes','isolation','cable',NULL),
('High Box Step Up','glutes','lunge','dumbbell',NULL),
-- TACTICAL
('Farmer Carries','tactical','carry','dumbbell',NULL),
('HISE Shrugs','tactical','isolation','barbell',NULL),
('Snatch Grip High Pulls','tactical','hinge','barbell',NULL),
('Ruck Hand Release Push Ups','tactical','horizontal_press','bodyweight',NULL),
('Zercher Shrugs','tactical','isolation','barbell',NULL),
('Zercher March','tactical','carry','barbell',NULL),
('Zercher Carry','tactical','carry','barbell',NULL),
('Sandbag Over Shoulder','tactical','hinge','bodyweight',NULL),
('Sandbag Ground to Overhead','tactical','hinge','bodyweight',NULL),
('Forward Scoop Med-Ball Throw','tactical','isolation','bodyweight',NULL),
('Suitcase Carry','tactical','carry','dumbbell',NULL),
('CAT Bench Press','tactical','horizontal_press','barbell',NULL),
('CAT Deadlift','tactical','hinge','barbell',NULL),
('CAT Squat','tactical','squat','barbell',NULL),
('Sled March','tactical','carry','machine',NULL),
('Sled Sprint','tactical','carry','machine',NULL),
('Hill Sprint','tactical','carry','bodyweight',NULL),
('Depth Push Ups','tactical','isolation','bodyweight',NULL),
('Dead Rows','tactical','horizontal_pull','barbell',NULL),
('Towel Pull Ups','tactical','vertical_pull','bodyweight',NULL),
('Trap Bar Jumps','tactical','isolation','barbell',NULL),
('Trap Bar Deadlift','tactical','hinge','barbell',NULL),
('Deficit Deadlift','tactical','hinge','barbell',NULL),
('Snatch Grip Shrugs','tactical','isolation','barbell',NULL),
('Yoke Carry','tactical','carry','machine',NULL),
('Farmer Holds (Timed)','tactical','carry','dumbbell',NULL),
('Backwards Med Ball Throw','tactical','isolation','bodyweight',NULL),
('Anderson Zercher Squat','tactical','squat','barbell',NULL),
('Anderson Split Squat','tactical','lunge','barbell',NULL),
('Tactical Pro-Agility Drill','tactical','carry','bodyweight',NULL),
('Dead Bench Press','tactical','horizontal_press','barbell',NULL),
('Barbell Good Morning','tactical','hinge','barbell',NULL),
('Rucking','tactical','carry','bodyweight',NULL),
('Heavy Sled Push','tactical','carry','machine',NULL),
('Squat / Lunge / Step-Up Complex','tactical','lunge','dumbbell',NULL),
('Neck Extensions','tactical','isolation','bodyweight',NULL),
('Neck Flexion','tactical','isolation','bodyweight',NULL),
('Lateral Neck Flexion','tactical','isolation','bodyweight',NULL),
('Neck Rotation','tactical','isolation','bodyweight',NULL),
('Juarez Valley Push Ups','tactical','horizontal_press','bodyweight',NULL),
('Juarez Valley Dips','tactical','horizontal_press','bodyweight',NULL),
-- ATHLETE
('Seated Box Jumps','athlete','isolation','bodyweight',NULL),
('Pogo Jumps','athlete','isolation','bodyweight',NULL),
('DB Jump Squat','athlete','isolation','dumbbell',NULL),
('Med Ball Slam','athlete','isolation','bodyweight',NULL),
('Lateral Med Ball Slam','athlete','isolation','bodyweight',NULL),
('Single Leg Pogos','athlete','isolation','bodyweight',NULL),
('Jump Rope','athlete','isolation','bodyweight',NULL),
('Broad Jump','athlete','isolation','bodyweight',NULL),
('Broad Jump Repeats','athlete','isolation','bodyweight',NULL),
('Rotational Med Ball Throws','athlete','isolation','bodyweight',NULL),
('Box Jump','athlete','isolation','bodyweight',NULL),
('KB Swing','athlete','hinge','kettlebell',NULL),
('Banded KB Swing','athlete','hinge','kettlebell',NULL),
('Skater Hops','athlete','isolation','bodyweight',NULL),
('Shin Hops','athlete','isolation','bodyweight',NULL),
('Shin Hop to Box Jump','athlete','isolation','bodyweight',NULL),
('Hurdle Hops','athlete','isolation','bodyweight',NULL),
('Depth Box Jump','athlete','isolation','bodyweight',NULL),
('Slideboard Push Ups','athlete','horizontal_press','bodyweight',NULL),
('Archer Pushups','athlete','horizontal_press','bodyweight',NULL),
('Single Leg Bounding','athlete','isolation','bodyweight',NULL),
('Explosive Alternating Lunges','athlete','isolation','bodyweight',NULL),
('Seated Weighted Box Jumps','athlete','isolation','dumbbell',NULL),
('Pro Agility Drill','athlete','carry','bodyweight',NULL),
-- CARDIO
('Incline Treadmill Walking','cardio','core','machine',NULL),
('Assault Bike','cardio','core','machine',NULL),
('Rower','cardio','core','machine',NULL),
('Run / Jog','cardio','core','bodyweight',NULL),
('Elliptical','cardio','core','machine',NULL),
('Sprint Intervals','cardio','core','bodyweight',NULL),
('Stairs','cardio','core','machine',NULL),
('Norwegian 4x4 Intervals','cardio','core','machine',NULL),
-- ABS / CORE
('Machine Crunches','abs','core','machine',NULL),
('KB Get-Up Sit Ups','abs','core','kettlebell',NULL),
('Cable Crunches','abs','core','cable',NULL),
('Med Ball Crunches','abs','core','bodyweight',NULL),
('Plank','abs','core','bodyweight',NULL),
('Side Plank','abs','core','bodyweight',NULL),
('Weighted Plank','abs','core','bodyweight',NULL),
('Plank Knees to Elbows','abs','core','bodyweight',NULL),
('Side Plank Crunch','abs','core','bodyweight',NULL),
('Hanging Knee Raise','abs','core','bodyweight',NULL),
('Hanging Leg Raise','abs','core','bodyweight',NULL),
('Elbow to Knee Crunches','abs','core','bodyweight',NULL),
('Leg Raise','abs','core','bodyweight',NULL),
('Flutter Kicks','abs','core','bodyweight',NULL),
('Flutter Kicks with Plate','abs','core','bodyweight',NULL),
('Hollow Rocks','abs','core','bodyweight',NULL),
('Hollow Hold','abs','core','bodyweight',NULL),
('Decline Sit Ups','abs','core','bodyweight',NULL),
('Army Sit Ups','abs','core','bodyweight',NULL),
('Oblique Crunches','abs','core','bodyweight',NULL),
('Hanging Oblique Raises','abs','core','bodyweight',NULL);
