-- TACTICAL / ATHLETE
insert into public.exercises (name, primary_muscle, movement_pattern, equipment, progression_eligible, suggested_rep_min, suggested_rep_max) values
('Farmer Carries', 'back', 'carry', 'dumbbell', false, 1, 1),
('HISE Shrugs', 'back', 'carry', 'barbell', true, 10, 20),
('Snatch Grip High Pulls', 'back', 'hinge', 'barbell', true, 3, 6),
('Ruck Hand Release Push Ups', 'chest', 'horizontal_press', 'bodyweight', false, 5, 15),
('Zercher Shrugs', 'back', 'carry', 'barbell', true, 8, 15),
('Zercher March', 'quads', 'carry', 'barbell', false, 1, 1),
('Suitcase Carry', 'back', 'carry', 'dumbbell', false, 1, 1),
('CAT Bench Press', 'chest', 'horizontal_press', 'barbell', true, 3, 6),
('CAT Deadlift', 'back', 'hinge', 'barbell', true, 2, 5),
('CAT Squat', 'quads', 'squat', 'barbell', true, 3, 6),
('Sled March', 'quads', 'carry', 'machine', false, 1, 1),
('Sled Sprint', 'quads', 'carry', 'machine', false, 1, 1),
('Hill Sprint', 'quads', 'carry', 'bodyweight', false, 1, 1),
('Depth Push Ups', 'chest', 'horizontal_press', 'bodyweight', false, 5, 15),
('Seated Box Jumps', 'quads', 'squat', 'bodyweight', false, 3, 8),
('Pogo Jumps', 'calves', 'isolation', 'bodyweight', false, 10, 30),
('Single Leg Pogos', 'calves', 'isolation', 'bodyweight', false, 8, 20),
('Jump Rope', 'calves', 'isolation', 'bodyweight', false, 1, 1),
('Broad Jump', 'quads', 'squat', 'bodyweight', false, 3, 8),
('Broad Jump Repeats', 'quads', 'squat', 'bodyweight', false, 5, 10),
('Trap Bar Jumps', 'quads', 'squat', 'barbell', false, 3, 6),
('Trap Bar Deadlift', 'back', 'hinge', 'barbell', true, 3, 8),
('Deficit Deadlift', 'back', 'hinge', 'barbell', true, 2, 5),
('Depth Box Jump', 'quads', 'squat', 'bodyweight', false, 3, 8),
('Snatch Grip Shrugs', 'back', 'isolation', 'barbell', true, 8, 15),
('Farmer Holds (Timed)', 'back', 'carry', 'dumbbell', false, 1, 1),
('Backwards Med Ball Throw', 'back', 'hinge', 'bodyweight', false, 3, 8),
('Anderson Zercher Squat', 'quads', 'squat', 'barbell', true, 3, 6),
('Anderson Split Squat', 'quads', 'lunge', 'barbell', true, 4, 8),
('Tactical Pro-Agility Drill', 'quads', 'carry', 'bodyweight', false, 1, 1),
('Skater Hops', 'quads', 'lunge', 'bodyweight', false, 8, 20),
('Shin Hops', 'quads', 'squat', 'bodyweight', false, 5, 15),
('Shin Hop to Box Jump', 'quads', 'squat', 'bodyweight', false, 4, 10),
('Hurdle Hops', 'quads', 'squat', 'bodyweight', false, 4, 10),
('Dead Bench Press', 'chest', 'horizontal_press', 'barbell', true, 2, 5),
('Barbell Good Morning', 'hamstrings', 'hinge', 'barbell', true, 6, 12),
('KB Swing', 'glutes', 'hinge', 'kettlebell', false, 10, 20),
('Banded KB Swing', 'glutes', 'hinge', 'kettlebell', false, 10, 20),
('Box Jump', 'quads', 'squat', 'bodyweight', false, 3, 8),
('Rucking', 'back', 'carry', 'bodyweight', false, 1, 1),
('Heavy Sled Push', 'quads', 'squat', 'machine', false, 1, 1),
('Med Ball Slam', 'back', 'hinge', 'bodyweight', false, 5, 15),
('Lateral Med Ball Slam', 'back', 'hinge', 'bodyweight', false, 5, 15),
('Rotational Med Ball Throws', 'back', 'hinge', 'bodyweight', false, 6, 12),
('DB Jump Squat', 'quads', 'squat', 'dumbbell', false, 4, 10);

-- CARDIO
insert into public.exercises (name, primary_muscle, movement_pattern, equipment, progression_eligible, suggested_rep_min, suggested_rep_max) values
('Incline Treadmill Walking', 'abs', 'core', 'machine', false, 1, 1),
('Assault Bike', 'abs', 'core', 'machine', false, 1, 1),
('Rower', 'back', 'horizontal_pull', 'machine', false, 1, 1),
('Run/Jog', 'abs', 'core', 'bodyweight', false, 1, 1),
('Elliptical', 'abs', 'core', 'machine', false, 1, 1),
('Sprint Intervals', 'quads', 'squat', 'bodyweight', false, 1, 1),
('Stairs', 'quads', 'squat', 'bodyweight', false, 1, 1),
('Norwegian 4x4 Intervals', 'abs', 'core', 'machine', false, 1, 1);

-- ABS / CORE / TRUNK
insert into public.exercises (name, primary_muscle, movement_pattern, equipment, progression_eligible, suggested_rep_min, suggested_rep_max) values
('Machine Crunches', 'abs', 'core', 'machine', true, 10, 20),
('KB Get-Up Sit Ups', 'abs', 'core', 'kettlebell', false, 6, 15),
('Cable Crunches', 'abs', 'core', 'cable', true, 12, 20),
('Med Ball Crunches', 'abs', 'core', 'bodyweight', false, 12, 20),
('Plank', 'abs', 'core', 'bodyweight', false, 1, 1),
('Side Plank', 'abs', 'core', 'bodyweight', false, 1, 1),
('Weighted Plank', 'abs', 'core', 'bodyweight', false, 1, 1),
('Plank Knees to Elbows', 'abs', 'core', 'bodyweight', false, 8, 20),
('Side Plank Crunch', 'abs', 'core', 'bodyweight', false, 8, 15),
('Hanging Knee Raise', 'abs', 'core', 'bodyweight', false, 10, 20),
('Hanging Leg Raise', 'abs', 'core', 'bodyweight', false, 8, 15),
('Elbow to Knee Crunches', 'abs', 'core', 'bodyweight', false, 12, 20),
('Leg Raise', 'abs', 'core', 'bodyweight', false, 10, 20),
('Flutter Kicks', 'abs', 'core', 'bodyweight', false, 15, 40),
('Flutter Kicks with Plate', 'abs', 'core', 'bodyweight', false, 15, 30),
('Hollow Rocks', 'abs', 'core', 'bodyweight', false, 10, 25),
('Hollow Hold', 'abs', 'core', 'bodyweight', false, 1, 1),
('Decline Sit Ups', 'abs', 'core', 'machine', false, 10, 20),
('Army Sit Ups', 'abs', 'core', 'bodyweight', false, 10, 20),
('Oblique Crunches', 'abs', 'core', 'bodyweight', false, 12, 20),
('Hanging Oblique Raises', 'abs', 'core', 'bodyweight', false, 8, 15);
